# Generated by Django 4.2.19 on 2025-03-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto'),
        ),
    ]
