# Generated by Django 5.2 on 2025-04-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_biodata_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '1. Biodata'},
        ),
    ]
